//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilmDBEntities : DbContext
    {
        public FilmDBEntities()
            : base("name=FilmDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Episodes> Episodes { get; set; }
        public virtual DbSet<Films> Films { get; set; }
        public virtual DbSet<Follows> Follows { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ViewLogs> ViewLogs { get; set; }
        public virtual DbSet<OTPs> OTPs { get; set; }
    }
}
