//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTPs
    {
        public string Email { get; set; }
        public string OtpCodeHashed { get; set; }
        public System.DateTime ExpiryTime { get; set; }
        public Nullable<bool> IsVerified { get; set; }
    }
}
