//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FilmApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4b6de16b3a606314de0b990f14e6fd50_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("4b6de16b3a606314de0b990f14e6fd50-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6fac0f71ff09b99ab1ecd791877ab5a5_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("6fac0f71ff09b99ab1ecd791877ab5a5-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap black_ribbon_app_icon_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("black_ribbon_app_icon-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_Line_Vector_Design_Images__Beautiful_Clock_Vector_Line_Icon__Clock_Icons__Line_Icons__Beautiful_Icons_PNG_Image_For_Free_Download_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Clock_Line_Vector_Design_Images__Beautiful_Clock_Vector_Line_Icon__Clock_Icons__L" +
                        "ine_Icons__Beautiful_Icons_PNG_Image_For_Free_Download-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__1__removebg_preview {
            get {
                object obj = ResourceManager.GetObject("download__1_-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("download-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap email {
            get {
                object obj = ResourceManager.GetObject("email", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap email1 {
            get {
                object obj = ResourceManager.GetObject("email1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f344cfb11133a1473fa462938f7776f3_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("f344cfb11133a1473fa462938f7776f3-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filmlogo {
            get {
                object obj = ResourceManager.GetObject("filmlogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filmlogo_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("filmlogo-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fotografi_Desain_Grafis_Ikon_Kamera_Template__Ikon_Kamera__Ikon_Fotografi__Ikon_Templat_PNG_dan_Vektor_dengan_Background_Transparan_untuk_Unduh_Gratis_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Fotografi_Desain_Grafis_Ikon_Kamera_Template__Ikon_Kamera__Ikon_Fotografi__Ikon_T" +
                        "emplat_PNG_dan_Vektor_dengan_Background_Transparan_untuk_Unduh_Gratis-removebg-p" +
                        "review", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Free_right_arrow_icon_png_vector___Pixsector__Free_vector_images__mockups__PSDs_and_photos_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Free_right_arrow_icon_png_vector_-_Pixsector__Free_vector_images__mockups__PSDs_a" +
                        "nd_photos-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Globe_Vector_Hd_PNG_Images__Vector_Globe_Icon__Globe_Icons__Globe_Icon__World_Icon_PNG_Image_For_Free_Download_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Globe_Vector_Hd_PNG_Images__Vector_Globe_Icon__Globe_Icons__Globe_Icon__World_Ico" +
                        "n_PNG_Image_For_Free_Download-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Google_Play_Store_icon_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Google_Play_Store_icon-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HD_Full_Screen_White_Icon_PNG_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("HD_Full_Screen_White_Icon_PNG-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap homeiccon {
            get {
                object obj = ResourceManager.GetObject("homeiccon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap homeiccon1 {
            get {
                object obj = ResourceManager.GetObject("homeiccon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MBE_Biểu_Tượng_Cây_Cỏ_Bốn_Lá_Dễ_Thương_Vector_Dễ_Thương___Công_cụ_đồ_họa_AI_Tải_xuống_miễn_phí___Pikbest_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("MBE_Biểu_Tượng_Cây_Cỏ_Bốn_Lá_Dễ_Thương_Vector_Dễ_Thương___Công_cụ_đồ_họa_AI_Tải_x" +
                        "uống_miễn_phí_-_Pikbest-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Purpose_Silhouette_PNG_Transparent__Movie_Icon_Which_Is_Designed_For_All_Application_Purpose_New__New_Icons__Application_Icons__Movie_Icons_PNG_Image_For_Free_Download_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Purpose_Silhouette_PNG_Transparent__Movie_Icon_Which_Is_Designed_For_All_Applicat" +
                        "ion_Purpose_New__New_Icons__Application_Icons__Movie_Icons_PNG_Image_For_Free_Do" +
                        "wnload-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Third_Eye_Illustration___Moonstone_Creative_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Third_Eye_Illustration___Moonstone_Creative-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Worlds_Silhouette_PNG_Transparent__World_Icon__World_Icons__World_Clipart__World_PNG_Image_For_Free_Download_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Worlds_Silhouette_PNG_Transparent__World_Icon__World_Icons__World_Clipart__World_" +
                        "PNG_Image_For_Free_Download-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Начало___Бесплатно_векторы_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Начало___Бесплатно_векторы-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
